pip install h5py --upgrade
pip install opencv-python --upgrade
pip install pandas --upgrade
pip install pillow --upgrade
pip install pydicom --upgrade
pip install tqdm --upgrade
pip install torchvision --upgrade
pip install scikit-image --upgrade
pip install scipy --upgrade
pip install numpy --upgrade